### ISSUE TITLE
求支持chatglm4

### ISSUE THREAD

**Issue by gitgitTrue** [ypwhs/CreativeChatGLM#50]
求支持chatglm4

**Comment by Rei1mu** [comment]
+1

**Comment by ypwhs** [comment]
需求get

**Comment by ypwhs** [comment]
已支持 GLM-4-9B：

![image](https://github.com/ypwhs/CreativeChatGLM/assets/10473170/2e820040-a657-40d2-bc9e-656190db6b06)
